# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:12

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-vue-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v4-vue-{{ .Branch }}-
            - v4-vue-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v4-vue-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./

  vuefire-core:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: cd packages/@posva/vuefire-core && yarn test
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/@posva/vuefire-core/coverage

  vuefire:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: cd packages/vuefire && yarn test
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/vuefire/coverage

  vuexfire:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: cd packages/vuexfire && yarn test
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/vuexfire/coverage

  coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn codecov

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - vuefire-core:
          requires:
            - install
      - vuefire:
          requires:
            - install
      - vuexfire:
          requires:
            - install
      - coverage:
          requires:
            - vuefire-core
            - vuefire
            - vuexfire
